### ISSUE TITLE
Item Number not work

### ISSUE THREAD

**Issue by waltervargas** [chromatic/Pod-PseudoPod-LaTeX#10]
Hi, 

I am using Pod::PseudoPod::LaTeX, and i have a problem with item numbered: 

Example: 

``` perl

=over

=item 1 RAM

=item 1 DD

Text

=item 1 Procesador

Text

=back

```

And my result in Latex  is : 

``` latex
\begin{description}

\setlength{\topsep}{0pt}
\setlength{\itemsep}{0pt}

\item 1 RAM

\item 1 DD

Text

\item 1 Procesador

Text

\end{description}

```

And I want the output: 

``` latex

\begin{enumerate}
\item ...
\end{enumerate}
```

**Comment by chromatic** [comment]
Fixed in release 1.20190901. Please upgrade Pod::PseudoPod to 0.19 and Pod::PseudoPod::LaTeX and let me know if this works for you.
