### ISSUE TITLE
ppod2latex --full

### ISSUE THREAD

**Issue by ambs** [chromatic/Pod-PseudoPod-LaTeX#11]
Create a flag to generate a full compilable document (standalone document), just like pod2html.

**Comment by moritz** [comment]
This was just implemented by @paultcochrane.

@chromatic, maybe you want to give him direct push access? He's been doing some good work these past days or weeks.

**Comment by paultcochrane** [comment]
Dunno if that's necessary just yet.  I've been scratching a couple of itches, since I want to use PPL in the xs-fun project.  What would be more useful would be an updated version of the dist on CPAN.  It would be awesome to have the more recent updates available via `cpanm`!

**Comment by moritz** [comment]
I've uploaded a new release to CPAN.
